---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ee-deployment
spec:
  selector:
    matchLabels:
      app: hello-ee 
  replicas: 20
  template:
    metadata:
      labels:
        app: hello-ee 
    spec:
      containers:
      - name: hello-ee 
        image: hello-ee-image:v1  
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ee-service
spec: 
  type:  
    LoadBalancer
  selector:
    app: hello-ee
  ports:
  - protocol: TCP
    port: 9999 
    targetPort: 9999

