version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run tests
          command: sudo pip install flake8 && flake8 . 
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:  
          name: Build backend image
          command: docker build -t $DOCKER_USER/hello-ee:$VERSION --build-arg version=$VERSION . && docker tag $DOCKER_USER/hello-ee:$VERSION $DOCKER_USER/hello-ee:latest
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS 
      - run:
          name: Docker push hello-ee image
          command: docker push $DOCKER_USER/hello-ee

  deploy_to_dev:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set Env Variables here
          command: echo "$VERSION and etc"
      - run:
          name : deploy to k8s
          command: echo "kubectl set image deployment hello-ee-deployment hello-ee=docker.io/pedroguima/hello-ee:$VERSION"
    

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_dev
